// <auto-generated />
using System;
using HotelManagementApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260508102144_UpdateAttractionModel")]
    partial class UpdateAttractionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagementApi.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Amenitie__3213E83FBD2AAAAE");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Articles__3213E83FE73B7D9B");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Articles__32DD1E4C0375A21D")
                        .IsUnique()
                        .HasFilter("[slug] IS NOT NULL");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("HotelManagementApi.Models.ArticleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Article___3213E83F71C963D5");

                    b.ToTable("Article_Categories", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("distance_km");

                    b.Property<string>("MapEmbedLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("map_embed_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Attracti__3213E83FC7416AF1");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("HotelManagementApi.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("table_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Audit_Lo__3213E83FC2A3F4BE");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("booking_code");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("guest_phone");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id")
                        .HasName("PK__Bookings__3213E83F1EDAA578");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.HasIndex(new[] { "BookingCode" }, "UQ__Bookings__FF29040F16585CE3")
                        .IsUnique();

                    b.HasIndex(new[] { "BookingCode" }, "UQ__Bookings__FF29040FF71AC35D")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelManagementApi.Models.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime")
                        .HasColumnName("check_out_date");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price_per_night");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id")
                        .HasName("PK__Booking___3213E83F9A5B3A64");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Booking_Details", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultPriceIfLost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStockQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<int>("InUseQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LiquidatedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("FinalTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("final_total");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("status");

                    b.Property<decimal?>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TotalRoomAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_room_amount");

                    b.Property<decimal?>("TotalServiceAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_service_amount");

                    b.HasKey("Id")
                        .HasName("PK__Invoices__3213E83F0D30A246");

                    b.HasIndex("BookingId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelManagementApi.Models.LossAndDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("penalty_amount");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("RoomInventoryId")
                        .HasColumnType("int")
                        .HasColumnName("room_inventory_id");

                    b.HasKey("Id")
                        .HasName("PK__Loss_And__3213E83FA34FFDFF");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("RoomInventoryId");

                    b.ToTable("Loss_And_Damages", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("discount_percent");

                    b.Property<int?>("MinPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("min_points");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tier_name");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83F173B8B61");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("ReferenceLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reference_link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Notifications");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingDetailId")
                        .HasColumnType("int")
                        .HasColumnName("booking_detail_id");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("PK__Order_Se__3213E83F6F6B15EA");

                    b.HasIndex("BookingDetailId");

                    b.ToTable("Order_Services", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.OrderServiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderServiceId")
                        .HasColumnType("int")
                        .HasColumnName("order_service_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PK__Order_Se__3213E83FC1F51539");

                    b.HasIndex("OrderServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Order_Service_Details", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transaction_code");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3213E83FE485D877");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Permissi__3213E83F8B67CE9B");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3213E83FBACFB23F");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83F6EA2DBE0");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Rooms__3213E83F2CCEEBC3");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id")
                        .HasName("PK__Room_Ima__3213E83F94AF0BB6");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Room_Images", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_type");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal?>("PriceIfLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price_if_lost");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("PK__Room_Inv__3213E83F33B187F1");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("Room_Inventory", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<int>("CapacityAdults")
                        .HasColumnType("int")
                        .HasColumnName("capacity_adults");

                    b.Property<int>("CapacityChildren")
                        .HasColumnType("int")
                        .HasColumnName("capacity_children");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Room_Typ__3213E83FF97313CB");

                    b.ToTable("Room_Types", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("PK__Services__3213E83F337130E4");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("HotelManagementApi.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Service___3213E83F59480DC6");

                    b.ToTable("Service_Categories", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int")
                        .HasColumnName("membership_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F1887AADB");

                    b.HasIndex("MembershipId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E61640F3C79AE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164DB0B057E")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("discount_value");

                    b.Property<decimal?>("MinBookingValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_booking_value");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("usage_limit");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("PK__Vouchers__3213E83F4BACC0A7");

                    b.HasIndex(new[] { "Code" }, "UQ__Vouchers__357D4CF932BA9E56")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Vouchers__357D4CF97FB14D96")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK__Role_Per__C85A546370DE4C7D");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role_Permissions", (string)null);
                });

            modelBuilder.Entity("RoomTypeAmenity", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int")
                        .HasColumnName("room_type_id");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int")
                        .HasColumnName("amenity_id");

                    b.HasKey("RoomTypeId", "AmenityId")
                        .HasName("PK__RoomType__8CA9DAD6AB9CB1C3");

                    b.HasIndex("AmenityId");

                    b.ToTable("RoomType_Amenities", (string)null);
                });

            modelBuilder.Entity("HotelManagementApi.Models.Article", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__Articles__author__51300E55");

                    b.HasOne("HotelManagementApi.Models.ArticleCategory", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Articles__catego__5224328E");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelManagementApi.Models.AuditLog", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Audit_Log__user___531856C7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Booking", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Bookings__user_i__06CD04F7");

                    b.HasOne("HotelManagementApi.Models.Voucher", "Voucher")
                        .WithMany("Bookings")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("FK__Bookings__vouche__07C12930");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("HotelManagementApi.Models.BookingDetail", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Booking_D__booki__03F0984C");

                    b.HasOne("HotelManagementApi.Models.Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__Booking_D__room___04E4BC85");

                    b.HasOne("HotelManagementApi.Models.RoomType", "RoomType")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__Booking_D__room___05D8E0BE");

                    b.Navigation("Booking");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Invoice", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Booking", "Booking")
                        .WithMany("Invoices")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Invoices__bookin__58D1301D");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelManagementApi.Models.LossAndDamage", b =>
                {
                    b.HasOne("HotelManagementApi.Models.BookingDetail", "BookingDetail")
                        .WithMany("LossAndDamages")
                        .HasForeignKey("BookingDetailId")
                        .HasConstraintName("FK__Loss_And___booki__59C55456");

                    b.HasOne("HotelManagementApi.Models.RoomInventory", "RoomInventory")
                        .WithMany("LossAndDamages")
                        .HasForeignKey("RoomInventoryId")
                        .HasConstraintName("FK__Loss_And___room___5AB9788F");

                    b.Navigation("BookingDetail");

                    b.Navigation("RoomInventory");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Notification", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__user___43210ABC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementApi.Models.OrderService", b =>
                {
                    b.HasOne("HotelManagementApi.Models.BookingDetail", "BookingDetail")
                        .WithMany("OrderServices")
                        .HasForeignKey("BookingDetailId")
                        .HasConstraintName("FK__Order_Ser__booki__0D7A0286");

                    b.Navigation("BookingDetail");
                });

            modelBuilder.Entity("HotelManagementApi.Models.OrderServiceDetail", b =>
                {
                    b.HasOne("HotelManagementApi.Models.OrderService", "OrderService")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("OrderServiceId")
                        .HasConstraintName("FK__Order_Ser__order__5BAD9CC8");

                    b.HasOne("HotelManagementApi.Models.Service", "Service")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__Order_Ser__servi__5CA1C101");

                    b.Navigation("OrderService");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Payment", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("FK__Payments__invoic__5E8A0973");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Review", b =>
                {
                    b.HasOne("HotelManagementApi.Models.RoomType", "RoomType")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__Reviews__room_ty__5F7E2DAC");

                    b.HasOne("HotelManagementApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reviews__user_id__607251E5");

                    b.Navigation("RoomType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Room", b =>
                {
                    b.HasOne("HotelManagementApi.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__Rooms__room_type__151B244E");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomImage", b =>
                {
                    b.HasOne("HotelManagementApi.Models.RoomType", "RoomType")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomTypeId")
                        .HasConstraintName("FK__Room_Imag__room___634EBE90");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomInventory", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("HotelManagementApi.Models.Room", "Room")
                        .WithMany("RoomInventories")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__Room_Inve__room___14270015");

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Service", b =>
                {
                    b.HasOne("HotelManagementApi.Models.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Services__catego__17F790F9");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HotelManagementApi.Models.User", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Membership", "Membership")
                        .WithMany("Users")
                        .HasForeignKey("MembershipId")
                        .HasConstraintName("FK__Users__membershi__18EBB532");

                    b.HasOne("HotelManagementApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__role_id__19DFD96B");

                    b.Navigation("Membership");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK__Role_Perm__permi__6166761E");

                    b.HasOne("HotelManagementApi.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Role_Perm__role___625A9A57");
                });

            modelBuilder.Entity("RoomTypeAmenity", b =>
                {
                    b.HasOne("HotelManagementApi.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomType___ameni__662B2B3B");

                    b.HasOne("HotelManagementApi.Models.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__RoomType___room___671F4F74");
                });

            modelBuilder.Entity("HotelManagementApi.Models.ArticleCategory", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("HotelManagementApi.Models.BookingDetail", b =>
                {
                    b.Navigation("LossAndDamages");

                    b.Navigation("OrderServices");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Membership", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HotelManagementApi.Models.OrderService", b =>
                {
                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Room", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("RoomInventories");
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomInventory", b =>
                {
                    b.Navigation("LossAndDamages");
                });

            modelBuilder.Entity("HotelManagementApi.Models.RoomType", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Reviews");

                    b.Navigation("RoomImages");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Service", b =>
                {
                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("HotelManagementApi.Models.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("HotelManagementApi.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("AuditLogs");

                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HotelManagementApi.Models.Voucher", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
